**MOMENTS**

If you consider a linear SISO system, described by the form: 

\begin{align}
\dot{x} &= Ax + Bu \\
y &= Cx
\end{align}

The transfer function is given by: 
\begin{equation}
W(s) = C(sI - A)^{-1} B
\end{equation}

One can define the 0-moment of the system at $s^* \in \bold{C}$ as: 
\begin{equation}
\eta_0 (s^*) = C(s^* I - A)^{-1} B
\end{equation}

The k-moment of the system at $s^* \in \bold{C}$ is the complex number: 
\begin{equation}
\eta_k ( s^* ) = \frac{ (-1)^k }{ k !} \left[ \frac{d^k}{ds^k} ( C(sI -A )^{-1} B) \right]
\end{equation}

As shown by Astolfi (1), 
There is a 1 to 1 relationship between each moments and the matrix $C \Pi$. 

$$ \tilde{x}_g = \tilde{\Pi}_g \chi_g \quad (\text{dimension } N_g - n)$$


In [3]:
import numpy as np
import scipy.linalg as la

# Simple 2nd-order plant
A = np.array([[0., 1.],
              [-2., -3.]])
B = np.array([[0.],
              [1.]])
C = np.array([[1., 0.]])

# Signal generator (forward moments)
Sg = np.array([[0., 1.],
               [-1., 0.]])  # sinusoidal oscillator (cos,sin)
Lg = np.array([[1., 0.]])   # input = first component of generator

# Solve Sylvester for Pi_g: A Pi_g + B Lg = Pi_g Sg
Pi_g = la.solve_sylvester(A, -Sg, -B @ Lg)
Mg = C @ Pi_g

# Output filter (backward moments)
Sf = np.array([[-5.]])   # stable 1st-order filter
Lf = np.array([[1.]])    # feed output directly

# Solve Sylvester for Pi_f: Pi_f A + Lf C = S_f Pi_f
Pi_f = la.solve_sylvester(A.T, -Sf.T, -(C.T @ Lf.T))
Pi_f = Pi_f.T  # adjust orientation
Mf = Pi_f @ B

Pi_g, Mg, Pi_f, Mf


(array([[ 0.1, -0.3],
        [ 0.3,  0.1]]),
 array([[ 0.1, -0.3]]),
 array([[-0.16666667,  0.08333333]]),
 array([[0.08333333]]))